services:
  - type: web
    name: future-frequencies
    buildCommand: npm install && npm run build
    startCommand: npm run start
    staticPublishPath: ./dist
    routes:
      - path: /*
        destination: /index.html
